AllCops:
  Exclude:
    - vendor/**/*
    - test/dummy/**/*
    - bin/**/*

Metrics/LineLength:
  Exclude:
    - activejob-scheduler.gemspec

Metrics/MethodLength:
  Exclude:
    - lib/active_job/scheduler/event.rb

Naming/FileName:
  Exclude:
    - lib/activejob-scheduler.rb
