language: ruby
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: rubygems
  api_key:
    secure: Pc0pTAFK72e7m47TnOg8f07MF8wrx5soR/D6K9VOT5+TWEPmYktVuoubsdNBc7Qf+MoTRdqbTeyvcqBI2BCuQUh98Ls8AC3pdmiz2WNNN8LFm3JYudLR/tRU2Fm6jsM5hE/Q6kdqCBEYgR1radwGv5IBBl9JjCs8amC2bVuJHBw=
  gem: activejob-scheduler
  on:
    tags: true
    repo: tubbo/activejob-scheduler
env:
  global:
    secure: QvIDmtMATWuUuPvqujou8wgClT5JgXiVwHzqort0a+ssLQsi5kMNw+AAiNyfgKc0OOlxgKEJkJr1LSgZpyOiVhmpJ88cItaLI3ngSCHZIYT+LqU31wxcTTmTqXpdgZymrHMdHmeInxkIvtC1kzLatIUF8XODA+CnXWjEVBT/HXc=
